spring.application.name=management
spring.datasource.url=jdbc:mysql://localhost:3306/db_bank?createDatabaseIfNotExist=true
#spring.datasource.username=read_write_only_user
spring.datasource.username=root
spring.datasource.password=Jinesh@77
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.envers.autoRegisterListeners=true
spring.jpa.properties.hibernate.envers.store_data_at_delete=true

#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.cache.type=redis
#AWS_ACCESS_KEY
#AWS_SECRET_KEY
#AWS_REGION
#MDS_SQS_URL

#spring.elasticsearch.rest.uris=http://localhost:9200
#spring.elasticsearch.uris
#spring.main.allow-circular-references

#elasticsearch.host=localhost
#elasticsearch.port=9200
#elasticsearch.scheme=http