spring.application.name=management
spring.datasource.url=jdbc:mysql://aws-a0001-aps1-1a-dev-rds-ostpl-mysql-development.cro33qwllhhn.ap-south-1.rds.amazonaws.com:3306/qa_backend_test_database_kartik?useUnicode=true&characterEncoding=UTF-8&useSSL=false
spring.datasource.username=read_write_only_user
spring.datasource.password=lZdHyuNcb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
